### PR TITLE
Examples config.yml structure

### PR DESCRIPTION
**Pull request by kimardenmiller**
- Added config.yml structure to run examples

- Updated README.md

### CODE REVIEW

**Comment by eviltrout** [comment]
This is quite interesting @oblakeerickson - on one hand it makes the examples much simpler but on the other each individual example is no longer standalone. What do you think?

**Comment by oblakeerickson** [comment]
Thanks for the PR and I know we have quite a bit of discussion about this [on meta](https://meta.discourse.org/t/building-tests-for-new-discourse-api-endpoints/118639/8?u=blake)

but I think @eviltrout brings up a good point about the examples probably should be standalone.

So, now that you have done a lot of the ground work already I think we can allow for some verbosity in the example code. 

Let's either remove or greatly slim down the example helper file so that it only does the YAML loading.

Then add these lines back into each example, but check to see if the yaml file exists first and load the values from the yaml file and if not just fall back to the example values (pseudo code).

```
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require File.expand_path('../../lib/discourse_api', __FILE__)

# load yml file

client = config['host'] || DiscourseApi::Client.new("http://localhost:3000")
client.api_key = config['api_key'] || "YOUR_API_KEY"
client.api_username = config['api_username'] || "YOUR_USERNAME"
 ```

This way someone who wants to get up and running quickly with the examples can have a good stand alone file to edit and refer to.

**Comment by kimardenmiller** [comment]
@oblakeerickson nearest I can figure to implement your pseudo code might be like so, testing for the host and proceeding as normal from there:

```
# frozen_string_literal: true
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require File.expand_path('../../lib/discourse_api', __FILE__)
require_relative 'example_helper'

config = load_yml
host = config['host'] || "http://localhost:3000"

client = DiscourseApi::Client.new host
client.api_key = config['api_key'] || "YOUR_API_KEY"
client.api_username = config['api_username'] || "YOUR_USERNAME"

# get badges
puts client.badges
```
Seems to lack symmetry somehow by treating 'host' differently. Ideas?

**Comment by oblakeerickson** [comment]
Hey! glad you are back to working on this :) 

I think you can leave off the host line and just do

```
client = DiscourseApi::Client.new (config['host'] || "http://localhost:3000")
```

**Comment by kimardenmiller** [comment]
That works. And for the example_helper I have:

```
# frozen_string_literal: true
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require File.expand_path('../../lib/discourse_api', __FILE__)
require 'yaml'

def load_yml
  config_yml = File.expand_path('../config.yml', __FILE__)

  begin
    config = YAML.load_file config_yml
  rescue Errno::ENOENT
    config = {}
  end
  config
end
```
Look good?

**Comment by kimardenmiller** [comment]
@oblakeerickson if that helper file structure looks good to you, I can commit and send this over today.

**Comment by oblakeerickson** [comment]
Yes this structure looks good, but let's use the DiscourseApi module inside of the example_helper and create a static class for loading the config. Then loading it will look like this:

```
config = DiscourseApi::ExampleHelper.load_yml
```

It is good convention to use the module name inside of a gem, and using a class let's us know where `load_yml` is coming from as well as keeping the function name isolated to the class.

**Comment by kimardenmiller** [comment]
Sounds good. By that logic would we also want to

- Place `ExampleHelper` in `lib/discourse_api`?

- Place `config_example.yml` and expect `config.yml` to be in the application root directory?

**Comment by oblakeerickson** [comment]
Yep, both of those would be good changes.

**Comment by kimardenmiller** [comment]
Last question: How do you feel about how I'm pathing to the config? Any other comments?

`# ExampleHelper`

```# frozen_string_literal: true
require 'yaml'

module DiscourseApi
  class ExampleHelper

    def self.load_yml
      config_yml = File.expand_path('../../../config.yml', __FILE__)
      puts config_yml
      begin
        config = YAML.load_file config_yml
      rescue Errno::ENOENT
        config = {}
      end
      config
    end
    
  end
end
```

```# Each example file```

```
# frozen_string_literal: true
$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require File.expand_path('../../lib/discourse_api', __FILE__)

config = DiscourseApi::ExampleHelper.load_yml

client = DiscourseApi::Client.new(config['host'] || 'http://localhost:3000')
client.api_key = config['api_key'] || "YOUR_API_KEY"
client.api_username = config['api_username'] || "YOUR_USERNAME"

# get badges
puts client.badges
```

Those top two load lines were like that before my time, but I don't seem to need the 
```$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)```
Can I remove that line?

**Comment by oblakeerickson** [comment]
I'm fine with all the `../`'s for now. There are probably better way to do it, but I don't think we need to worry about it at the moment.

No. I don't think you can remove those top two lines, they are so you can run that file without having the gem installed. This way you can edit an example and run it without having to publish your private changes to rubygems.

**Comment by kimardenmiller** [comment]
> I don't think you can remove those top two lines, they are so you can run that file without having the gem installed. This way you can edit an example and run it without having to publish your private changes to rubygems.

Ah, on further testing I see that the first line is not needed within the discourse_api project itself (e.g. the current examples files), but appears to be needed once you locate a file outside the project. Got it.

Please see PR #189 .

**Pull request closed without merging**
