### PR TITLE
Example config.yml Support

### PR DESCRIPTION
**Pull request by kimardenmiller**
- Example files now read config.yml file when present for client settings

### CODE REVIEW

**Comment by kimardenmiller** [comment]
I see the `cannot load such file -- rubocop-discourse` in Travis, but am not sure why that's happening. RuboCop is running fine for me locally with no failures or warnings.

**Comment by oblakeerickson** [comment]
I'm not sure why Travis is throwing that error either. 

But there is a whitespace issue to fix:

```
Offenses:

lib/discourse_api/example_helper.rb:17:1: C: Layout/TrailingWhitespace: Trailing whitespace detected.
```

**Comment by oblakeerickson** [comment]
Ah, it is because of a recent rubocop change in discourse core. I asked a question about it here:

https://review.discourse.org/t/dev-use-rubocop-discourse-gem-to-add-custom-chdir-cop/7111/3?u=blake

**Comment by kimardenmiller** [comment]
If you want me to add that dev dependency, just point me in the right direction.

Also, are you generally able to amend to commits to fix up small issues like this one? Seems in the past I might have tried that and created an extra merge we didn't like. Guidance there would be helpful as well.

**Comment by kimardenmiller** [comment]
What else is needed besides installing rubocop-discourse?

Locally I'm getting:
```
Error:Rubocop returned exit code: 2
stderr:
[Warn] Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.
https://github.com/rubocop-hq/rubocop/tree/master/manual/migrate_performance_cops.md
cannot load such file -- rubocop-discourse
/Users/kimardenmiller/.rbenv/versions/2.6.2/gemsets/discourse_api/gems/rubocop-0.67.2/lib/rubocop/config_loader_resolver.rb:15:in `require'
/Users/kimardenmiller/.rbenv/versions/2.6.2/gemsets/discourse_api/gems/rubocop-0.67.2/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/Users/kimardenmiller/.rbenv/versions/2.6.2/gemsets/discourse_api/gems/rubocop-0.67.2/lib/rubocop/config_loader_resolver.rb:11:in `each'
/Users/kimardenmiller/.rbenv/versions/2.6.2/gemsets/discourse_api/gems/rubocop-0.67.2/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/Users/kimardenmiller/.rbenv/versions/2.6.2/gemsets/discourse_api/gems/rubocop-0.67.2/lib/rubocop/config_loader.rb:44:in `load_file'
/Users/kimardenmiller/.rbenv/versions/2.6.2/gemsets/discourse_api/gems/ ...
```

**Comment by oblakeerickson** [comment]
Did you pull master yet? I made two small commits.

You might need to run bundle install?

**Comment by kimardenmiller** [comment]
Git Pull solved it. Thanks!

**Pull request merged**
