### PR TITLE
- Created 3 poll methods for endpoints

### PR DESCRIPTION
**Pull request by kimardenmiller**
- poll vote
- toggle poll status
- poll voters
- RuboCop Fixes

### CODE REVIEW

**Comment by kimardenmiller** [comment]
Started over cherry picking into an up-to-date branch. Better?

**Comment by oblakeerickson** [comment]
Awesome, thanks! :tada:

**Comment by kimardenmiller** [comment]
NP. I have a couple more PRs I held back on to make sure I understand the runway. So I'll take that approach: get a fresh branch and cherry pick the one commit. Anything else to note before I send over these others?

I think you had a desire to clean up some reused links in the tests with it's own PR?

**Comment by oblakeerickson** [comment]
Oh cool, glad you have more! :)

Just make sure you do one PR for each "feature/change".

> I think you had a desire to clean up some reused links in the tests with it's own PR?

Yes, I think it would be handy if the examples read the host, username, and api_key, out of a single file rather than copy and pasting them in every file. Then the user could replace the default values with env variables. This way you can easily run many of the examples without editing any code.

**Comment by kimardenmiller** [comment]
One coming PR adds allowed access to the . update_user method, expanding this list:
https://github.com/discourse/discourse_api/blob/e6dff8c0b84e8b0df4693fd824513ba8ab834b6e/lib/discourse_api/api/users.rb#L34

But I'm wondering if this is a case we want to specify .optional, as the list was created incomplete, I added some I happen to need, but the list of possible fields here is long and subject to frequent change. Do we actually want to try and maintain exactly the correct list? Furthering the issue is the fact that the API currently fails silently when an attempted field is not on the list. Thoughts?

**Comment by kimardenmiller** [comment]
> Yes, I think it would be handy if the examples read the host, username, and api_key, out of a single file rather than copy and pasting them in every file. Then the user could replace the default values with env variables. This way you can easily run many of the examples without editing any code.

Do you envision that single file being spec_helper or a new file, if a new file, what location?

**Comment by oblakeerickson** [comment]
I think it should read from a new file called config.yml but don’t actually
commit that file. Probably should add it to gitignore. Create and fill out
config-example.yml with dummy data that can be copied to config.yml.

**Comment by kimardenmiller** [comment]
Okey dokey. Have not created a yml yet, so good learning experience.

Kim

**Comment by kimardenmiller** [comment]
Where would we like to place and load things? 

Right now I have in the discourse_api.rb file (w/config.yml in root dir):

```
require 'yaml'
CONFIG = YAML.load_file(File.expand_path('../../config.yml', __FILE__))
```

... then in each example file:

```
client = DiscourseApi::Client.new(CONFIG['host'])
client.api_key = CONFIG['api_key']
client.api_username = CONFIG['api_username']
```

That works for the examples, but not for the tests I don't think. How would you suggest we wire this up?

**Comment by oblakeerickson** [comment]
This is only for the examples though right?

**Comment by kimardenmiller** [comment]
Thought your request came from this convo over referencing host in the tests:

https://meta.discourse.org/t/building-tests-for-new-discourse-api-endpoints/118639/4

**Comment by kimardenmiller** [comment]
Apologies. I should have started this conversation over there, but did not have my hands on it at the time. I'm happy to cover both cases in this PR.

**Pull request merged**
