### PR TITLE
Upgrade bundler version

### PR DESCRIPTION
**Pull request by nisevi**
As discussed here https://github.com/discourse/discourse_api/pull/171 we are upgrading the `bundler` version 🚀

### CODE REVIEW

**Comment by nisevi** [comment]
I believe TravisCI will fail @oblakeerickson

**Comment by oblakeerickson** [comment]
Looks like we also should update our .travis ruby versions so that TravisCI will pass.

> There are no versions of rubygems-update (= 3.0.3) compatible with your Ruby & RubyGems
	rubygems-update requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.

I'm fine if we update them to latest 2.5.x and 2.6.x

**Comment by nisevi** [comment]
Done 👍  @oblakeerickson

**Comment by oblakeerickson** [comment]
Awesome thanks! :smile_cat:

**Pull request merged**
