### PR TITLE
Adds user topic and replies functions

### PR DESCRIPTION
**Pull request by dngrhm**
Adds functions to get replies by username and topics and replies by username

### CODE REVIEW

**Comment by oblakeerickson** [comment]
Hey thank you for the pull-request!

Something is weird because these commits are from 2016 and it doesn't merge cleanly because of your Merge commit. Could you somehow rebase this with the current master and squash your current commits so there is only one?

The other thing is that you have some hard coded numbers on the filters. I'm not sure if we want to hard code these but maybe make them defaults.

**Comment by dngrhm** [comment]
Yes commits are from 2016 to add this functionality that we needed at the time.  I've been updating the apps to semi-modern rails.  This forced updating our fork of discourse_api to a recent version.

I'll look into rebasing the PR.  

I'm not sure on what you mean by the proposed change.  Make the hard coded numbers default values for an argument fo the functions? That doesn't entirely make sense as the numbers correspond to what the function is filtering.  Please correct me if my understanding is off here.

**Comment by oblakeerickson** [comment]
Sorry, I see what is going on now, we can leave the hard coded values in.

**Comment by dngrhm** [comment]
@oblakeerickson Thanks for your consideration of this PR and for the feedback.  The branch has been rebased onto master and squashed to 1 commit.  Let me know if you see any other needed changes.  Thanks for maintaining the project!

**Comment by oblakeerickson** [comment]
Thanks! gem version 0.26.0 has your change :)

**Pull request merged**
