### PR TITLE
Add all_users to list all existing users

### PR DESCRIPTION
**Pull request by kuon**
Add a way to list all users in a discourse system.

### CODE REVIEW

**Comment by oblakeerickson** [comment]
@kuon Thanks! I'll review this when I get a chance later today.

**Comment by oblakeerickson** [comment]
@kuon does `list_users` not do what you want? https://github.com/discourse/discourse_api/pull/110

**Comment by kuon** [comment]
list_users is limited to 100 for some reason

**Comment by oblakeerickson** [comment]
Okay, I understand what you did now.

I really really appreciate this commit, but I think we should work on a fix in discourse/discourse first and see if we can fix the actual /admin/user API endpoint to return all the users.

**Comment by oblakeerickson** [comment]
@kuon 

What if we start by resolving this issue:

https://github.com/discourse/discourse_api/issues/105

Can you submit another PR with a change to the [groups section](https://github.com/discourse/discourse_api/blob/master/lib/discourse_api/api/groups.rb) 

I feel like the [`group_members` method](https://github.com/discourse/discourse_api/blob/master/lib/discourse_api/api/groups.rb) you wrote is doing too much.

I think if you re-write it so that it doesn't do any paging, but you have to pass in the `group_id`, `limit`, and `offset` I would merge that in.

Then until we get discourse/discourse fixed to return all the users, you could still call your new group_members method from your own application code with a loop to get all the users.

**Comment by kuon** [comment]
Yeah I realize it is somewhat a hack, but I thought the gem would update faster than discourse itself.

**Comment by kuon** [comment]
There is also one other thing I was wondering, this call requires a group name to be passed in, not a group id.

I can rename the `group_id` var to `group_name` but I am wondering if it is ok or if you want `group_members` to accept an id and do an API call to resolve the name.

**Comment by oblakeerickson** [comment]
I think group_name is good, lets go with that.

**Comment by kuon** [comment]
Do you prefer:

```ruby
def group_members(group_name, limit = 100, offset = 0)
end
```

or

```ruby
# This version let you omit the limit while specifying the offset
def group_members(group_name, offset = 0, limit = 100)
end
```

or

```ruby
# Use keyword arguments?
def group_members(group_name, offset: 0, limit: 100)
end
```

If you fix discourse endpoint to accept offset and limit all over the place, I'd rather get it right.

**Comment by oblakeerickson** [comment]
Well. I like the second version. I like the default of 100 and then just specifying the offset if you want more than 100 with multiple calls.

We've been working on converting most things over to using the [params hash](https://github.com/discourse/discourse_api/blob/f082a5f82e0aa3adc94d196c777d99fbe2164797/lib/discourse_api/api/params.rb) if you would like try and use that that.

There are a few examples in the [users.rb](https://github.com/discourse/discourse_api/blob/f082a5f82e0aa3adc94d196c777d99fbe2164797/lib/discourse_api/api/users.rb) file, but most of the files are using it somewhere if you need more examples of how to use it.

**Comment by kuon** [comment]
I went the params way if it's the future: https://github.com/discourse/discourse_api/pull/111

**Pull request closed without merging**
