### PR TITLE
Add post actions such as likes and flags

### PR DESCRIPTION
**Pull request by BYWallace**
This PR adds post actions, which include likes and the different types of flags based on the ID that's passed in. They can be created, destroyed and retrieved for a specific post along with the user that committed the action.

Thoughts? Feedback much appreciated!

### CODE REVIEW

**Comment by oblakeerickson** [comment]
Sweet! I'll check it out.

**Comment by oblakeerickson** [comment]
Thank you for making this by the way! I have a few suggestions though: 

1. Lets not create a new module. Go ahead and use the existing post and topic modules
2. Let's remove the `flag_topic` parameter from the `create_post_action` and instead create its own method in the topics module called `create_topic_action`.
3. Add some examples to the examples folder.

**Comment by BYWallace** [comment]
Sounds good! Figuring out the best way to set up `create_topic_action`. Does the following do the trick or is there a better way to make sure the flag is `true` on those requests?

```
 def create_topic_action(args)
      args = API.params(args)
                 .required(:id, :post_action_type_id)
                 .default(flag_topic: true)
      post("/post_actions", args)
 end
```

**Comment by oblakeerickson** [comment]
Yes that would do the trick.... but we don't want the flag_topic to be changed (someone could still pass in `flag_topic: false`) so I would remove it from the `API.params` section and modify the `args` variable to hard code the `flag_topic: true` value before you pass it into post().

If you have any more questions just let me know!

**Comment by BYWallace** [comment]
Ready for a pass!

**Comment by oblakeerickson** [comment]
sweet thanks! I'll cut a new gem version sometime today or tomorrow.

**Pull request merged**
