### PR TITLE
- Created 3 poll methods for endpoints & tests

### PR DESCRIPTION
**Pull request by kimardenmiller**
- poll_vote
 - toggle_poll_status
 - poll_voters

### CODE REVIEW

**Comment by oblakeerickson** [comment]
Thanks for submitting this PR. We are using rubocop now to keep things consistent in this code base as well as with the main discourse code base. Could you look at the rubocop offenses listed here: https://travis-ci.org/discourse/discourse_api/jobs/551532631 and get those resolved. Thanks!

**Comment by kimardenmiller** [comment]
Ok, should be good to go now. :)
Kim

**Comment by oblakeerickson** [comment]
Your poll changes look good, but I think you merged from an old branch or something because you had to re-do a bunch of changes already in master for `client.rb`. If you do a get pull --rebase origin master will it pull those in?

**Comment by kimardenmiller** [comment]
Better now?

**Comment by oblakeerickson** [comment]
Nope, it's worse :( 

image

Sorry, I think you needed to:

- revert your changes to client.rb and commit
- git checkout master
- get pull origin master
- git checkout <your branch>
- git merge --rebase master
- then update your pr.

I'll play around with your branch tomorrow and see if can get it right. It should only be showing your commits.

**Comment by oblakeerickson** [comment]
Closing in favor of https://github.com/discourse/discourse_api/pull/177

**Pull request closed without merging**
