### PR TITLE
Update Posts#post_action_users for 1.5 endpoint

### PR DESCRIPTION
**Pull request by eric-hu**
- Add a unit test and fixture for post_action_users
- Add a fixture for post_action_users
  - Fixture taken from a Discuss 1.6.1 live instance (text values changed)
- Tested locally against current (9/1) master branch on discourse/discourse

### CODE REVIEW

**Comment by eric-hu** [comment]
The post_action_users endpoint is useful for fetching additional information like the users who have "liked" a post.  When I tested against my local copy of Discourse, it didn't have this data in there, so I only verified that the API endpoint exists.

**Comment by oblakeerickson** [comment]
@eric-hu awesome thanks!! I will check it out later tonight/tomorrow when I get a chance

**Comment by eric-hu** [comment]
Looking forward to it!  I bumped the Ruby 2.2 teeny version from 2.2.3 to 2.2.5 so the 2.2 branch tests would run on Travis.

**Comment by oblakeerickson** [comment]
Thanks!

**Pull request merged**
