### PR TITLE
Test hostname extraction

### PR DESCRIPTION
**Pull request by kimardenmiller**
- Per request: [Building Tests for New discourse_api Endpoints](https://meta.discourse.org/t/building-tests-for-new-discourse-api-endpoints/118639).

### CODE REVIEW

**Comment by kimardenmiller** [comment]
Seeing failed checks, but don't see how they relate to my changes. I have all 145 tests passing locally.

**Comment by oblakeerickson** [comment]
Sweet thanks for the PR. Those errors are related to a new faraday version. if you run bundle install you should get the new version, and see the errors. Care you make another PR for the Faraday fix?

I think all you will need to do is find all occurrences for `Faraday::Error::ClientError` and replace it with `Faraday::ClientError`

**Comment by kimardenmiller** [comment]
My faraday seems to be staying at 0.15.4, where I think gemlock has it. So I'm not able to reproduce the error locally. Should I bundle update faraday to bump the gemlock to 0.16.2 ?

**Comment by oblakeerickson** [comment]
Let's continue this discussion on https://meta.discourse.org/t/fix-faraday-deprecations-in-discourse-api-gem/129974?u=blake

**Pull request merged**
